### ISSUE TITLE
Error when training stage 2

### ISSUE THREAD

**Issue by exityan** [cvlab-yonsei/ISGAN#1]
Hi,

Your work is very impressive and I tried training with market1501 dataset.
But I encountered an error like below when I trained stage 2.

```
$ python main.py --mode train --data_path ./datasets/market1501 --stage 2
...
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main.train()
  File "main.py", line 54, in train
    G_loss = self.loss(inputs, labels, batch)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/ISGAN/loss.py", line 202, in forward
    = self.GAN_loss(inputs, outputs, labels)
  File "/workspace/ISGAN/loss.py", line 136, in GAN_loss
    D_real, C_real = self.model.D(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/ISGAN/network.py", line 356, in forward
    avgp = self.avgp(label_D1).squeeze(dim=3).squeeze(dim=2)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 554, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (256x11x3). Calculated output size: (256x0x0). Output size is too small
```

I think it's because in Discriminator module `AvgPool2d`'s kernel size(12, 4) is larger than its input data size(11, 3).

Can you give me any help about this?

Thank you.

**Comment by shyamalagig** [comment]
@exityan did you solved this issue?

**Comment by consilium538** [comment]
if network.py:299 change from
https://github.com/cvlab-yonsei/ISGAN/blob/e987a59481632de76095f6dc66d217f3285f4d2a/network.py#L296-L301 to
```python
kw = 3
```
everything work well
